version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Asia/Tokyo
    cooldown:
      default-days: 5
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Asia/Tokyo
    assignees:
      - minguu42
    cooldown:
      default-days: 5
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directory: /infra/terraform
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Asia/Tokyo
    cooldown:
      default-days: 5
    groups:
      dependencies:
        patterns:
          - "*"
