DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id         BIGINT    PRIMARY KEY AUTO_INCREMENT,
    name       CHAR(255) NOT NULL UNIQUE,
    token      CHAR(64)  NOT NULL UNIQUE,
    created_at DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tasks (
    id           BIGINT    PRIMARY KEY AUTO_INCREMENT,
    user_id      BIGINT    NOT NULL,
    title        CHAR(255) NOT NULL,
    completed_at DATETIME,
    created_at   DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
