// Code generated by ogen, DO NOT EDIT.
package ogen

type DeleteTaskRes interface {
	deleteTaskRes()
}

type GetHealthRes interface {
	getHealthRes()
}

type GetTasksRes interface {
	getTasksRes()
}

type PatchTaskRes interface {
	patchTaskRes()
}

type PostTasksRes interface {
	postTasksRes()
}
