// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"time"

	"github.com/go-faster/errors"
)

type CreateProjectBadRequest ErrorResponse

func (*CreateProjectBadRequest) createProjectRes() {}

type CreateProjectInternalServerError ErrorResponse

func (*CreateProjectInternalServerError) createProjectRes() {}

type CreateProjectNotImplemented ErrorResponse

func (*CreateProjectNotImplemented) createProjectRes() {}

type CreateProjectReq struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *CreateProjectReq) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *CreateProjectReq) SetName(val string) {
	s.Name = val
}

type CreateProjectUnauthorized ErrorResponse

func (*CreateProjectUnauthorized) createProjectRes() {}

type CreateTaskBadRequest ErrorResponse

func (*CreateTaskBadRequest) createTaskRes() {}

type CreateTaskInternalServerError ErrorResponse

func (*CreateTaskInternalServerError) createTaskRes() {}

type CreateTaskNotFound ErrorResponse

func (*CreateTaskNotFound) createTaskRes() {}

type CreateTaskNotImplemented ErrorResponse

func (*CreateTaskNotImplemented) createTaskRes() {}

type CreateTaskReq struct {
	Title string `json:"title"`
}

// GetTitle returns the value of Title.
func (s *CreateTaskReq) GetTitle() string {
	return s.Title
}

// SetTitle sets the value of Title.
func (s *CreateTaskReq) SetTitle(val string) {
	s.Title = val
}

type CreateTaskUnauthorized ErrorResponse

func (*CreateTaskUnauthorized) createTaskRes() {}

type DeleteProjectBadRequest ErrorResponse

func (*DeleteProjectBadRequest) deleteProjectRes() {}

type DeleteProjectInternalServerError ErrorResponse

func (*DeleteProjectInternalServerError) deleteProjectRes() {}

// DeleteProjectNoContent is response for DeleteProject operation.
type DeleteProjectNoContent struct{}

func (*DeleteProjectNoContent) deleteProjectRes() {}

type DeleteProjectNotFound ErrorResponse

func (*DeleteProjectNotFound) deleteProjectRes() {}

type DeleteProjectNotImplemented ErrorResponse

func (*DeleteProjectNotImplemented) deleteProjectRes() {}

type DeleteProjectUnauthorized ErrorResponse

func (*DeleteProjectUnauthorized) deleteProjectRes() {}

type DeleteTaskBadRequest ErrorResponse

func (*DeleteTaskBadRequest) deleteTaskRes() {}

type DeleteTaskInternalServerError ErrorResponse

func (*DeleteTaskInternalServerError) deleteTaskRes() {}

// DeleteTaskNoContent is response for DeleteTask operation.
type DeleteTaskNoContent struct{}

func (*DeleteTaskNoContent) deleteTaskRes() {}

type DeleteTaskNotFound ErrorResponse

func (*DeleteTaskNotFound) deleteTaskRes() {}

type DeleteTaskNotImplemented ErrorResponse

func (*DeleteTaskNotImplemented) deleteTaskRes() {}

type DeleteTaskUnauthorized ErrorResponse

func (*DeleteTaskUnauthorized) deleteTaskRes() {}

type ErrorResponse struct {
	// ユーザ向けの大まかなエラーの説明.
	Message string `json:"message"`
	// 開発者向けの詳細なエラーの説明.
	Debug string `json:"debug"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// GetDebug returns the value of Debug.
func (s *ErrorResponse) GetDebug() string {
	return s.Debug
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

// SetDebug sets the value of Debug.
func (s *ErrorResponse) SetDebug(val string) {
	s.Debug = val
}

type GetHealthNotImplemented ErrorResponse

func (*GetHealthNotImplemented) getHealthRes() {}

type GetHealthOK struct {
	// MTasks APIのバージョン.
	Version string `json:"version"`
	// MTasks APIのリビジョン.
	Revision string `json:"revision"`
}

// GetVersion returns the value of Version.
func (s *GetHealthOK) GetVersion() string {
	return s.Version
}

// GetRevision returns the value of Revision.
func (s *GetHealthOK) GetRevision() string {
	return s.Revision
}

// SetVersion sets the value of Version.
func (s *GetHealthOK) SetVersion(val string) {
	s.Version = val
}

// SetRevision sets the value of Revision.
func (s *GetHealthOK) SetRevision(val string) {
	s.Revision = val
}

func (*GetHealthOK) getHealthRes() {}

type GetHealthServiceUnavailable ErrorResponse

func (*GetHealthServiceUnavailable) getHealthRes() {}

type IsAuthorized struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *IsAuthorized) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *IsAuthorized) SetAPIKey(val string) {
	s.APIKey = val
}

type ListProjectsBadRequest ErrorResponse

func (*ListProjectsBadRequest) listProjectsRes() {}

type ListProjectsInternalServerError ErrorResponse

func (*ListProjectsInternalServerError) listProjectsRes() {}

type ListProjectsNotImplemented ErrorResponse

func (*ListProjectsNotImplemented) listProjectsRes() {}

type ListProjectsSort string

const (
	ListProjectsSortCreatedAt      ListProjectsSort = "createdAt"
	ListProjectsSortMinusCreatedAt ListProjectsSort = "-createdAt"
)

// MarshalText implements encoding.TextMarshaler.
func (s ListProjectsSort) MarshalText() ([]byte, error) {
	switch s {
	case ListProjectsSortCreatedAt:
		return []byte(s), nil
	case ListProjectsSortMinusCreatedAt:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListProjectsSort) UnmarshalText(data []byte) error {
	switch ListProjectsSort(data) {
	case ListProjectsSortCreatedAt:
		*s = ListProjectsSortCreatedAt
		return nil
	case ListProjectsSortMinusCreatedAt:
		*s = ListProjectsSortMinusCreatedAt
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ListProjectsUnauthorized ErrorResponse

func (*ListProjectsUnauthorized) listProjectsRes() {}

type ListTasksBadRequest ErrorResponse

func (*ListTasksBadRequest) listTasksRes() {}

type ListTasksInternalServerError ErrorResponse

func (*ListTasksInternalServerError) listTasksRes() {}

type ListTasksNotFound ErrorResponse

func (*ListTasksNotFound) listTasksRes() {}

type ListTasksNotImplemented ErrorResponse

func (*ListTasksNotImplemented) listTasksRes() {}

type ListTasksSort string

const (
	ListTasksSortCreatedAt      ListTasksSort = "createdAt"
	ListTasksSortMinusCreatedAt ListTasksSort = "-createdAt"
)

// MarshalText implements encoding.TextMarshaler.
func (s ListTasksSort) MarshalText() ([]byte, error) {
	switch s {
	case ListTasksSortCreatedAt:
		return []byte(s), nil
	case ListTasksSortMinusCreatedAt:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListTasksSort) UnmarshalText(data []byte) error {
	switch ListTasksSort(data) {
	case ListTasksSortCreatedAt:
		*s = ListTasksSortCreatedAt
		return nil
	case ListTasksSortMinusCreatedAt:
		*s = ListTasksSortMinusCreatedAt
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ListTasksUnauthorized ErrorResponse

func (*ListTasksUnauthorized) listTasksRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListProjectsSort returns new OptListProjectsSort with value set to v.
func NewOptListProjectsSort(v ListProjectsSort) OptListProjectsSort {
	return OptListProjectsSort{
		Value: v,
		Set:   true,
	}
}

// OptListProjectsSort is optional ListProjectsSort.
type OptListProjectsSort struct {
	Value ListProjectsSort
	Set   bool
}

// IsSet returns true if OptListProjectsSort was set.
func (o OptListProjectsSort) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListProjectsSort) Reset() {
	var v ListProjectsSort
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListProjectsSort) SetTo(v ListProjectsSort) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListProjectsSort) Get() (v ListProjectsSort, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListProjectsSort) Or(d ListProjectsSort) ListProjectsSort {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListTasksSort returns new OptListTasksSort with value set to v.
func NewOptListTasksSort(v ListTasksSort) OptListTasksSort {
	return OptListTasksSort{
		Value: v,
		Set:   true,
	}
}

// OptListTasksSort is optional ListTasksSort.
type OptListTasksSort struct {
	Value ListTasksSort
	Set   bool
}

// IsSet returns true if OptListTasksSort was set.
func (o OptListTasksSort) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListTasksSort) Reset() {
	var v ListTasksSort
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListTasksSort) SetTo(v ListTasksSort) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListTasksSort) Get() (v ListTasksSort, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListTasksSort) Or(d ListTasksSort) ListTasksSort {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Project
type Project struct {
	// プロジェクトID.
	ID int64 `json:"id"`
	// プロジェクト名.
	Name string `json:"name"`
	// 作成日時.
	CreatedAt time.Time `json:"createdAt"`
	// 更新日時.
	UpdatedAt time.Time `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Project) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *Project) GetName() string {
	return s.Name
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Project) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Project) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Project) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Project) SetName(val string) {
	s.Name = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Project) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Project) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Project) createProjectRes() {}
func (*Project) updateProjectRes() {}

// Ref: #/components/schemas/Projects
type Projects struct {
	// プロジェクト一覧.
	Projects []Project `json:"projects"`
}

// GetProjects returns the value of Projects.
func (s *Projects) GetProjects() []Project {
	return s.Projects
}

// SetProjects sets the value of Projects.
func (s *Projects) SetProjects(val []Project) {
	s.Projects = val
}

func (*Projects) listProjectsRes() {}

// Ref: #/components/schemas/Task
type Task struct {
	// タスクID.
	ID int64 `json:"id"`
	// 紐づくプロジェクトのID.
	ProjectID int64 `json:"project_id"`
	// タイトル.
	Title string `json:"title"`
	// 完了日時.
	CompletedAt OptDateTime `json:"completedAt"`
	// 作成日時.
	CreatedAt time.Time `json:"createdAt"`
	// 更新日時.
	UpdatedAt time.Time `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Task) GetID() int64 {
	return s.ID
}

// GetProjectID returns the value of ProjectID.
func (s *Task) GetProjectID() int64 {
	return s.ProjectID
}

// GetTitle returns the value of Title.
func (s *Task) GetTitle() string {
	return s.Title
}

// GetCompletedAt returns the value of CompletedAt.
func (s *Task) GetCompletedAt() OptDateTime {
	return s.CompletedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Task) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Task) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Task) SetID(val int64) {
	s.ID = val
}

// SetProjectID sets the value of ProjectID.
func (s *Task) SetProjectID(val int64) {
	s.ProjectID = val
}

// SetTitle sets the value of Title.
func (s *Task) SetTitle(val string) {
	s.Title = val
}

// SetCompletedAt sets the value of CompletedAt.
func (s *Task) SetCompletedAt(val OptDateTime) {
	s.CompletedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Task) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Task) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Task) createTaskRes() {}
func (*Task) updateTaskRes() {}

// Ref: #/components/schemas/Tasks
type Tasks struct {
	// タスク一覧.
	Tasks []Task `json:"tasks"`
}

// GetTasks returns the value of Tasks.
func (s *Tasks) GetTasks() []Task {
	return s.Tasks
}

// SetTasks sets the value of Tasks.
func (s *Tasks) SetTasks(val []Task) {
	s.Tasks = val
}

func (*Tasks) listTasksRes() {}

type UpdateProjectBadRequest ErrorResponse

func (*UpdateProjectBadRequest) updateProjectRes() {}

type UpdateProjectInternalServerError ErrorResponse

func (*UpdateProjectInternalServerError) updateProjectRes() {}

type UpdateProjectNotFound ErrorResponse

func (*UpdateProjectNotFound) updateProjectRes() {}

type UpdateProjectNotImplemented ErrorResponse

func (*UpdateProjectNotImplemented) updateProjectRes() {}

type UpdateProjectReq struct {
	Name OptString `json:"name"`
}

// GetName returns the value of Name.
func (s *UpdateProjectReq) GetName() OptString {
	return s.Name
}

// SetName sets the value of Name.
func (s *UpdateProjectReq) SetName(val OptString) {
	s.Name = val
}

type UpdateProjectUnauthorized ErrorResponse

func (*UpdateProjectUnauthorized) updateProjectRes() {}

type UpdateTaskBadRequest ErrorResponse

func (*UpdateTaskBadRequest) updateTaskRes() {}

type UpdateTaskInternalServerError ErrorResponse

func (*UpdateTaskInternalServerError) updateTaskRes() {}

type UpdateTaskNotFound ErrorResponse

func (*UpdateTaskNotFound) updateTaskRes() {}

type UpdateTaskNotImplemented ErrorResponse

func (*UpdateTaskNotImplemented) updateTaskRes() {}

type UpdateTaskReq struct {
	IsCompleted OptBool `json:"isCompleted"`
}

// GetIsCompleted returns the value of IsCompleted.
func (s *UpdateTaskReq) GetIsCompleted() OptBool {
	return s.IsCompleted
}

// SetIsCompleted sets the value of IsCompleted.
func (s *UpdateTaskReq) SetIsCompleted(val OptBool) {
	s.IsCompleted = val
}

type UpdateTaskUnauthorized ErrorResponse

func (*UpdateTaskUnauthorized) updateTaskRes() {}
