// Code generated by ogen, DO NOT EDIT.
package ogen

type CreateProjectRes interface {
	createProjectRes()
}

type CreateTaskRes interface {
	createTaskRes()
}

type DeleteProjectRes interface {
	deleteProjectRes()
}

type DeleteTaskRes interface {
	deleteTaskRes()
}

type GetHealthRes interface {
	getHealthRes()
}

type ListProjectsRes interface {
	listProjectsRes()
}

type ListTasksRes interface {
	listTasksRes()
}

type UpdateProjectRes interface {
	updateProjectRes()
}

type UpdateTaskRes interface {
	updateTaskRes()
}
