// Code generated by ogen, DO NOT EDIT.
package ogen

type DeleteProjectRes interface {
	deleteProjectRes()
}

type DeleteTaskRes interface {
	deleteTaskRes()
}

type GetHealthRes interface {
	getHealthRes()
}

type GetProjectsRes interface {
	getProjectsRes()
}

type GetTasksRes interface {
	getTasksRes()
}

type PatchProjectRes interface {
	patchProjectRes()
}

type PatchTaskRes interface {
	patchTaskRes()
}

type PostProjectsRes interface {
	postProjectsRes()
}

type PostTasksRes interface {
	postTasksRes()
}
