// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CheckHealth implements checkHealth operation.
//
// GET /health
func (UnimplementedHandler) CheckHealth(ctx context.Context) (r *CheckHealthOK, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProject implements createProject operation.
//
// POST /projects
func (UnimplementedHandler) CreateProject(ctx context.Context, req *CreateProjectReq) (r *Project, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateStep implements createStep operation.
//
// POST /tasks/{taskID}/steps
func (UnimplementedHandler) CreateStep(ctx context.Context, req *CreateStepReq, params CreateStepParams) (r *Step, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTag implements createTag operation.
//
// POST /tags
func (UnimplementedHandler) CreateTag(ctx context.Context, req *CreateTagReq) (r *Tag, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTask implements createTask operation.
//
// POST /projects/{projectID}/tasks
func (UnimplementedHandler) CreateTask(ctx context.Context, req *CreateTaskReq, params CreateTaskParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteProject implements deleteProject operation.
//
// DELETE /projects/{projectID}
func (UnimplementedHandler) DeleteProject(ctx context.Context, params DeleteProjectParams) error {
	return ht.ErrNotImplemented
}

// DeleteStep implements deleteStep operation.
//
// DELETE /tasks/{taskID}/steps/{stepID}
func (UnimplementedHandler) DeleteStep(ctx context.Context, params DeleteStepParams) error {
	return ht.ErrNotImplemented
}

// DeleteTag implements deleteTag operation.
//
// DELETE /tags/{tagID}
func (UnimplementedHandler) DeleteTag(ctx context.Context, params DeleteTagParams) error {
	return ht.ErrNotImplemented
}

// DeleteTask implements deleteTask operation.
//
// DELETE /projects/{projectID}/tasks/{taskID}
func (UnimplementedHandler) DeleteTask(ctx context.Context, params DeleteTaskParams) error {
	return ht.ErrNotImplemented
}

// GetProject implements GetProject operation.
//
// GET /projects/{projectID}
func (UnimplementedHandler) GetProject(ctx context.Context, params GetProjectParams) (r *Project, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTag implements getTag operation.
//
// GET /tags/{tagID}
func (UnimplementedHandler) GetTag(ctx context.Context, params GetTagParams) (r *Tag, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTask implements GetTask operation.
//
// GET /projects/{projectID}/tasks/{taskID}
func (UnimplementedHandler) GetTask(ctx context.Context, params GetTaskParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProjects implements listProjects operation.
//
// GET /projects
func (UnimplementedHandler) ListProjects(ctx context.Context, params ListProjectsParams) (r *Projects, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTags implements listTags operation.
//
// GET /tags
func (UnimplementedHandler) ListTags(ctx context.Context, params ListTagsParams) (r *Tags, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTasks implements listTasks operation.
//
// GET /projects/{projectID}/tasks
func (UnimplementedHandler) ListTasks(ctx context.Context, params ListTasksParams) (r *Tasks, _ error) {
	return r, ht.ErrNotImplemented
}

// SignIn implements signIn operation.
//
// POST /sign-in
func (UnimplementedHandler) SignIn(ctx context.Context, req *SignInReq) (r *SignInOK, _ error) {
	return r, ht.ErrNotImplemented
}

// SignUp implements signUp operation.
//
// POST /sign-up
func (UnimplementedHandler) SignUp(ctx context.Context, req *SignUpReq) (r *SignUpOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProject implements updateProject operation.
//
// PATCH /projects/{projectID}
func (UnimplementedHandler) UpdateProject(ctx context.Context, req *UpdateProjectReq, params UpdateProjectParams) (r *Project, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateStep implements updateStep operation.
//
// PATCH /tasks/{taskID}/steps/{stepID}
func (UnimplementedHandler) UpdateStep(ctx context.Context, req *UpdateStepReq, params UpdateStepParams) (r *Step, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTag implements updateTag operation.
//
// PATCH /tags/{tagID}
func (UnimplementedHandler) UpdateTag(ctx context.Context, req *UpdateTagReq, params UpdateTagParams) (r *Tag, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTask implements updateTask operation.
//
// PATCH /projects/{projectID}/tasks/{taskID}
func (UnimplementedHandler) UpdateTask(ctx context.Context, req *UpdateTaskReq, params UpdateTaskParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}
