// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CheckHealth implements CheckHealth operation.
//
// GET /health
func (UnimplementedHandler) CheckHealth(ctx context.Context) (r *CheckHealthOK, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProject implements CreateProject operation.
//
// POST /projects
func (UnimplementedHandler) CreateProject(ctx context.Context, req *CreateProjectReq) (r *Project, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateStep implements CreateStep operation.
//
// POST /tasks/{taskID}/steps
func (UnimplementedHandler) CreateStep(ctx context.Context, req *CreateStepReq, params CreateStepParams) (r *Step, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTag implements CreateTag operation.
//
// POST /tags
func (UnimplementedHandler) CreateTag(ctx context.Context, req *CreateTagReq) (r *Tag, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTask implements CreateTask operation.
//
// POST /projects/{projectID}/tasks
func (UnimplementedHandler) CreateTask(ctx context.Context, req *CreateTaskReq, params CreateTaskParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteProject implements DeleteProject operation.
//
// DELETE /projects/{projectID}
func (UnimplementedHandler) DeleteProject(ctx context.Context, params DeleteProjectParams) error {
	return ht.ErrNotImplemented
}

// DeleteStep implements DeleteStep operation.
//
// DELETE /steps/{stepID}
func (UnimplementedHandler) DeleteStep(ctx context.Context, params DeleteStepParams) error {
	return ht.ErrNotImplemented
}

// DeleteTag implements DeleteTag operation.
//
// DELETE /tags/{tagID}
func (UnimplementedHandler) DeleteTag(ctx context.Context, params DeleteTagParams) error {
	return ht.ErrNotImplemented
}

// DeleteTask implements DeleteTask operation.
//
// DELETE /tasks/{taskID}
func (UnimplementedHandler) DeleteTask(ctx context.Context, params DeleteTaskParams) error {
	return ht.ErrNotImplemented
}

// GetProject implements GetProject operation.
//
// GET /projects/{projectID}
func (UnimplementedHandler) GetProject(ctx context.Context, params GetProjectParams) (r *Project, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTag implements GetTag operation.
//
// GET /tags/{tagID}
func (UnimplementedHandler) GetTag(ctx context.Context, params GetTagParams) (r *Tag, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTask implements GetTask operation.
//
// GET /tasks/{taskID}
func (UnimplementedHandler) GetTask(ctx context.Context, params GetTaskParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProjects implements ListProjects operation.
//
// GET /projects
func (UnimplementedHandler) ListProjects(ctx context.Context, params ListProjectsParams) (r *ListProjectsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTags implements ListTags operation.
//
// GET /tags
func (UnimplementedHandler) ListTags(ctx context.Context, params ListTagsParams) (r *ListTagsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTasks implements ListTasks operation.
//
// GET /projects/{projectID}/tasks
func (UnimplementedHandler) ListTasks(ctx context.Context, params ListTasksParams) (r *ListTasksOK, _ error) {
	return r, ht.ErrNotImplemented
}

// SignIn implements SignIn operation.
//
// POST /sign-in
func (UnimplementedHandler) SignIn(ctx context.Context, req *SignInReq) (r *SignInOK, _ error) {
	return r, ht.ErrNotImplemented
}

// SignUp implements SignUp operation.
//
// POST /sign-up
func (UnimplementedHandler) SignUp(ctx context.Context, req *SignUpReq) (r *SignUpOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProject implements UpdateProject operation.
//
// PATCH /projects/{projectID}
func (UnimplementedHandler) UpdateProject(ctx context.Context, req *UpdateProjectReq, params UpdateProjectParams) (r *Project, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateStep implements UpdateStep operation.
//
// PATCH /steps/{stepID}
func (UnimplementedHandler) UpdateStep(ctx context.Context, req *UpdateStepReq, params UpdateStepParams) (r *Step, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTag implements UpdateTag operation.
//
// PATCH /tags/{tagID}
func (UnimplementedHandler) UpdateTag(ctx context.Context, req *UpdateTagReq, params UpdateTagParams) (r *Tag, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTask implements UpdateTask operation.
//
// PATCH /tasks/{taskID}
func (UnimplementedHandler) UpdateTask(ctx context.Context, req *UpdateTaskReq, params UpdateTaskParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}
