// Code generated by ogen, DO NOT EDIT.

package oapi

import (
	"fmt"
	"time"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

type CheckHealthOK struct {
	Revision string `json:"revision"`
}

// GetRevision returns the value of Revision.
func (s *CheckHealthOK) GetRevision() string {
	return s.Revision
}

// SetRevision sets the value of Revision.
func (s *CheckHealthOK) SetRevision(val string) {
	s.Revision = val
}

type CreateProjectReq struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

// GetName returns the value of Name.
func (s *CreateProjectReq) GetName() string {
	return s.Name
}

// GetColor returns the value of Color.
func (s *CreateProjectReq) GetColor() string {
	return s.Color
}

// SetName sets the value of Name.
func (s *CreateProjectReq) SetName(val string) {
	s.Name = val
}

// SetColor sets the value of Color.
func (s *CreateProjectReq) SetColor(val string) {
	s.Color = val
}

type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/project
type Project struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	Color      string    `json:"color"`
	IsArchived bool      `json:"is_archived"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Project) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Project) GetName() string {
	return s.Name
}

// GetColor returns the value of Color.
func (s *Project) GetColor() string {
	return s.Color
}

// GetIsArchived returns the value of IsArchived.
func (s *Project) GetIsArchived() bool {
	return s.IsArchived
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Project) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Project) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Project) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Project) SetName(val string) {
	s.Name = val
}

// SetColor sets the value of Color.
func (s *Project) SetColor(val string) {
	s.Color = val
}

// SetIsArchived sets the value of IsArchived.
func (s *Project) SetIsArchived(val bool) {
	s.IsArchived = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Project) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Project) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

type SignInOK struct {
	IDToken string `json:"id_token"`
}

// GetIDToken returns the value of IDToken.
func (s *SignInOK) GetIDToken() string {
	return s.IDToken
}

// SetIDToken sets the value of IDToken.
func (s *SignInOK) SetIDToken(val string) {
	s.IDToken = val
}

type SignInReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *SignInReq) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *SignInReq) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *SignInReq) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *SignInReq) SetPassword(val string) {
	s.Password = val
}

type SignUpOK struct {
	IDToken string `json:"id_token"`
}

// GetIDToken returns the value of IDToken.
func (s *SignUpOK) GetIDToken() string {
	return s.IDToken
}

// SetIDToken sets the value of IDToken.
func (s *SignUpOK) SetIDToken(val string) {
	s.IDToken = val
}

type SignUpReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *SignUpReq) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *SignUpReq) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *SignUpReq) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *SignUpReq) SetPassword(val string) {
	s.Password = val
}
