// Code generated by ogen, DO NOT EDIT.

package oapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CheckHealth implements checkHealth operation.
	//
	// GET /health
	CheckHealth(ctx context.Context) (*CheckHealthOK, error)
	// CreateProject implements createProject operation.
	//
	// POST /projects
	CreateProject(ctx context.Context, req *CreateProjectReq) (*Project, error)
	// ListProjects implements listProjects operation.
	//
	// GET /projects
	ListProjects(ctx context.Context, params ListProjectsParams) (*Projects, error)
	// SignIn implements signIn operation.
	//
	// POST /sign-in
	SignIn(ctx context.Context, req *SignInReq) (*SignInOK, error)
	// SignUp implements signUp operation.
	//
	// POST /sign-up
	SignUp(ctx context.Context, req *SignUpReq) (*SignUpOK, error)
	// UpdateProject implements updateProject operation.
	//
	// PATCH /projects/{projectID}
	UpdateProject(ctx context.Context, req *UpdateProjectReq, params UpdateProjectParams) (*Project, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
