// Code generated by ogen, DO NOT EDIT.

package openapi

// setDefaults set default value of fields.
func (s *CreateProjectReq) setDefaults() {
	{
		val := CreateProjectReqColor("default")
		s.Color.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateTaskReq) setDefaults() {
	{
		val := int(0)
		s.Priority.SetTo(val)
	}
}
