### PostProjects
POST http://localhost:8080/projects
Accept: application/json
Content-Type: application/json
X-Api-Key: rAM9Fm9huuWEKLdCwHBcju9Ty_-TL2tDsAicmMrXmUnaCGp3RtywzYpMDPdEtYtR

{
  "name": "プロジェクト1"
}

### GetProjects
GET http://localhost:8080/projects
Accept: application/json
X-Api-Key: rAM9Fm9huuWEKLdCwHBcju9Ty_-TL2tDsAicmMrXmUnaCGp3RtywzYpMDPdEtYtR

### PatchProject
PATCH http://localhost:8080/projects/1
Accept: application/json
Content-Type: application/json
X-Api-Key: rAM9Fm9huuWEKLdCwHBcju9Ty_-TL2tDsAicmMrXmUnaCGp3RtywzYpMDPdEtYtR

{
  "name": "プロジェクト2"
}

### DeleteProject
DELETE http://localhost:8080/projects/1
X-Api-Key: rAM9Fm9huuWEKLdCwHBcju9Ty_-TL2tDsAicmMrXmUnaCGp3RtywzYpMDPdEtYtR
