// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CheckHealth implements CheckHealth operation.
	//
	// GET /health
	CheckHealth(ctx context.Context) (*CheckHealthOK, error)
	// CreateProject implements CreateProject operation.
	//
	// POST /projects
	CreateProject(ctx context.Context, req *CreateProjectReq) (*Project, error)
	// CreateStep implements CreateStep operation.
	//
	// POST /tasks/{taskID}/steps
	CreateStep(ctx context.Context, req *CreateStepReq, params CreateStepParams) (*Step, error)
	// CreateTag implements CreateTag operation.
	//
	// POST /tags
	CreateTag(ctx context.Context, req *CreateTagReq) (*Tag, error)
	// CreateTask implements CreateTask operation.
	//
	// POST /projects/{projectID}/tasks
	CreateTask(ctx context.Context, req *CreateTaskReq, params CreateTaskParams) (*Task, error)
	// DeleteProject implements DeleteProject operation.
	//
	// DELETE /projects/{projectID}
	DeleteProject(ctx context.Context, params DeleteProjectParams) error
	// DeleteStep implements DeleteStep operation.
	//
	// DELETE /steps/{stepID}
	DeleteStep(ctx context.Context, params DeleteStepParams) error
	// DeleteTag implements DeleteTag operation.
	//
	// DELETE /tags/{tagID}
	DeleteTag(ctx context.Context, params DeleteTagParams) error
	// DeleteTask implements DeleteTask operation.
	//
	// DELETE /tasks/{taskID}
	DeleteTask(ctx context.Context, params DeleteTaskParams) error
	// GetProject implements GetProject operation.
	//
	// GET /projects/{projectID}
	GetProject(ctx context.Context, params GetProjectParams) (*Project, error)
	// GetTag implements GetTag operation.
	//
	// GET /tags/{tagID}
	GetTag(ctx context.Context, params GetTagParams) (*Tag, error)
	// GetTask implements GetTask operation.
	//
	// GET /tasks/{taskID}
	GetTask(ctx context.Context, params GetTaskParams) (*Task, error)
	// ListProjects implements ListProjects operation.
	//
	// GET /projects
	ListProjects(ctx context.Context, params ListProjectsParams) (*ListProjectsOK, error)
	// ListTags implements ListTags operation.
	//
	// GET /tags
	ListTags(ctx context.Context, params ListTagsParams) (*ListTagsOK, error)
	// ListTasks implements ListTasks operation.
	//
	// GET /projects/{projectID}/tasks
	ListTasks(ctx context.Context, params ListTasksParams) (*ListTasksOK, error)
	// SignIn implements SignIn operation.
	//
	// POST /sign-in
	SignIn(ctx context.Context, req *SignInReq) (*SignInOK, error)
	// SignUp implements SignUp operation.
	//
	// POST /sign-up
	SignUp(ctx context.Context, req *SignUpReq) (*SignUpOK, error)
	// UpdateProject implements UpdateProject operation.
	//
	// PATCH /projects/{projectID}
	UpdateProject(ctx context.Context, req *UpdateProjectReq, params UpdateProjectParams) (*Project, error)
	// UpdateStep implements UpdateStep operation.
	//
	// PATCH /steps/{stepID}
	UpdateStep(ctx context.Context, req *UpdateStepReq, params UpdateStepParams) (*Step, error)
	// UpdateTag implements UpdateTag operation.
	//
	// PATCH /tags/{tagID}
	UpdateTag(ctx context.Context, req *UpdateTagReq, params UpdateTagParams) (*Tag, error)
	// UpdateTask implements UpdateTask operation.
	//
	// PATCH /tasks/{taskID}
	UpdateTask(ctx context.Context, req *UpdateTaskReq, params UpdateTaskParams) (*Task, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
