// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CheckHealthOperation   OperationName = "CheckHealth"
	CreateProjectOperation OperationName = "CreateProject"
	CreateStepOperation    OperationName = "CreateStep"
	CreateTagOperation     OperationName = "CreateTag"
	CreateTaskOperation    OperationName = "CreateTask"
	DeleteProjectOperation OperationName = "DeleteProject"
	DeleteStepOperation    OperationName = "DeleteStep"
	DeleteTagOperation     OperationName = "DeleteTag"
	DeleteTaskOperation    OperationName = "DeleteTask"
	GetProjectOperation    OperationName = "GetProject"
	GetTagOperation        OperationName = "GetTag"
	GetTaskOperation       OperationName = "GetTask"
	ListProjectsOperation  OperationName = "ListProjects"
	ListTagsOperation      OperationName = "ListTags"
	ListTasksOperation     OperationName = "ListTasks"
	SignInOperation        OperationName = "SignIn"
	SignUpOperation        OperationName = "SignUp"
	UpdateProjectOperation OperationName = "UpdateProject"
	UpdateStepOperation    OperationName = "UpdateStep"
	UpdateTagOperation     OperationName = "UpdateTag"
	UpdateTaskOperation    OperationName = "UpdateTask"
)
