/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIDTasksRouteImport } from './routes/projects.$projectID.tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIDTasksRoute = ProjectsProjectIDTasksRouteImport.update({
  id: '/projects/$projectID/tasks',
  path: '/projects/$projectID/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectID/tasks': typeof ProjectsProjectIDTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$projectID/tasks': typeof ProjectsProjectIDTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$projectID/tasks': typeof ProjectsProjectIDTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/$projectID/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/$projectID/tasks'
  id: '__root__' | '/' | '/projects/$projectID/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectIDTasksRoute: typeof ProjectsProjectIDTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectID/tasks': {
      id: '/projects/$projectID/tasks'
      path: '/projects/$projectID/tasks'
      fullPath: '/projects/$projectID/tasks'
      preLoaderRoute: typeof ProjectsProjectIDTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectIDTasksRoute: ProjectsProjectIDTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
