openapi: 3.0.3
info:
  title: Harmattan API
  version: 0.1.0
paths:
  /sign-up:
    post:
      tags: [authentication]
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  format: password
              required: [email, password]
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_token:
                    type: string
                required: [id_token]
        default:
          $ref: "#/components/responses/error"
  /sign-in:
    post:
      tags: [authentication]
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  format: password
              required: [email, password]
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_token:
                    type: string
                required: [id_token]
        default:
          $ref: "#/components/responses/error"
  /projects:
    post:
      tags: [projects]
      operationId: createProject
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 20
                color:
                  type: string
                  minLength: 7
                  maxLength: 7
              required: [name, color]
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/project"
        default:
          $ref: "#/components/responses/error"
      security:
        - idTokenAuth: []
  /health:
    get:
      tags: [monitoring]
      operationId: checkHealth
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  revision:
                    type: string
                required: [revision]
        default:
          $ref: "#/components/responses/error"
components:
  schemas:
    project:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        color:
          type: string
        is_archived:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required: [id, name, color, is_archived, created_at, updated_at]
  responses:
    error:
      description: Error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
            required: [code, message]
  securitySchemes:
    idTokenAuth:
      type: http
      scheme: Bearer
tags:
  - name: authentication
  - name: projects
  - name: monitoring
