name: Integrate Go application

on: push

jobs:
  check-style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: goimports -l .
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: go vet $(go list ./... | grep -v /gen)
      - run: staticcheck $(go list ./... | grep -v /gen)
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - run: go install github.com/tenntenn/testtime/cmd/testtime@latest
      - run: go test -overlay=`testtime` $(go list ./... | grep -v /gen)
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - run: go build ./...
